### PR TITLE
Fix missing distro names in rpm targets

### LINKED ISSUE #875: [BUG] Printing targets for containers is not formatted properly.
### Expected Behavior

When running
```sh
docker buildx build --call targets --build-arg BUILDKIT_SYNTAX=ghcr.io/project-dalec/dalec/frontend:latest - <<< "null" | grep 'container ('
```

output is correctly formatted with `.`

### Actual Behavior

```console
$ docker buildx build --call targets --build-arg BUILDKIT_SYNTAX=ghcr.io/project-dalec/dalec/frontend:latest - <<< "null" | grep 'container ('
[+] Building 0.5s (3/3) FINISHED                                                                        docker-container:retina
 => resolve image config for docker-image://ghcr.io/project-dalec/dalec/frontend:latest                                    0.3s
 => CACHED docker-image://ghcr.io/project-dalec/dalec/frontend:latest@sha256:28aa75eb10152fb297f1c585ea2de75a2c62ceb4c904  0.0s
 => => resolve ghcr.io/project-dalec/dalec/frontend:latest@sha256:28aa75eb10152fb297f1c585ea2de75a2c62ceb4c904fe1483c4f8f  0.0s
 => [internal] load build definition from Dockerfile                                                                       0.0s
 => => transferring dockerfile: 42B                                                                                        0.0s
almalinux8/container (default)   Builds a container image for
almalinux9/container (default)   Builds a container image for
azlinux3/container (default)     Builds a container image for
mariner2/container (default)     Builds a container image for
rockylinux8/container (default)  Builds a container image for
rockylinux9/container (default)  Builds a container image for
windowscross/container (default) Builds binaries and installs them into a Windows base image
```

```go
	mux.Add("container", linux.HandleContainer(cfg), &targets.Target{
		Name:        "container",
		Description: "Builds a container image for " + cfg.FullName,
		Default:     true,
	})
```

It seems FullName appears empty.

### Steps To Reproduce

1. Run `docker buildx build --call targets --build-arg BUILDKIT_SYNTAX=ghcr.io/project-dalec/dalec/frontend:latest - <<< "null" | grep 'container ('`.

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #875 

Also adds a command to generate target docs.
Ideally this would be underneath adjacent to the doc file itself, however because the website currently lives in another go module it complicates the `go generate ./...` case.

Meanwhile the go module for the website is purely to make it run in a dagger container so it can be executed without extra tooling on the machine.
We could probably remove this separate module and do something different in a separate change.

### CODE REVIEW

File: cmd/gen-doc-targets/main.go [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+		}
+
+		f, err := os.OpenFile(flag.Arg(0), os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0644)
+		if err != nil {
+			fmt.Fprintf(os.Stderr, "failed to open output file: %v\n", err)
+			os.Exit(1)
+		}
+		defer f.Close()
+		out = f
+	}
```
Comment (DannyBrito) [inline cmd/gen-doc-targets/main.go:57]: not a must but wouldn't you want to validate the flags right at the beginning before processing everything else?

Comment (cpuguy83) [reply cmd/gen-doc-targets/main.go:57]: Yeah, I suppose so.
Artifact of how I iterated on this.
I think this is fine, especially given the use case.
It would be weird for someone to do something wrong here and even then its a relatively cheap oops since this doesn't need to roundtrip through buildkit or anything.
