### PR TITLE
Various improvements to testing

### LINKED ISSUE #476: [BUG] Integration tests possible not reporting failures
### Expected Behavior

https://github.com/Azure/dalec/actions/runs/12283069321/job/34275695113?pr=472#step:9:158,
It seems that the test is timeout or not really sure the cause but there is a panic and CI is not failing.
Not sure if that is expected?

### Actual Behavior

I would expect the integration tests to mark CI as failure

### Steps To Reproduce

_No response_

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

### PR DESCRIPTION
**Pull request by cpuguy83**
- Add some missing `t.Parallal()` and `startTestSpan` calls
- Fix test log output to print line by line instead of per read
- Use the same cache keys for the main Dockerfile and the test fixtures
- Add test stats to GHA summary
- Get tracing reports from integration tests
- Remove GH cache since this wasn't really giving us anything, and maybe was even slowing things down
- ci: Fix issue reporting failures from test panic
- ci: Split integration tests per distro into separate jobs

Supersedes #482 
Fixes #476

### CODE REVIEW

**Comment by cpuguy83** [comment]
The test failure is actually on main... I'm bisecting this now.

**Comment by cpuguy83** [comment]
Pushed commit to fix.

File: test/testenv/buildx.go [hunk 1]
```diff
@@ -290,7 +290,6 @@ func (b *BuildxEnv) RunTest(ctx context.Context, t *testing.T, f TestFunc, opts
 
 	var so client.SolveOpt
 	withProjectRoot(t, &so)
-	withGHCache(t, &so)
```
Comment (adamperlin) [inline test/testenv/buildx.go:293]: Do we have any idea why the GH cache was so slow?

Comment (cpuguy83) [reply test/testenv/buildx.go:293]: A couple of things:

1. It's just slow to transfer all that
2. The cache is going to get overwritten by each PR
3. Having separate cache scopes for each test, as is done here, means very little reuse between tests and just a bloated cache.

All in all, I found that the cache wasn't giving us any speedup.

Comment (adamperlin) [reply test/testenv/buildx.go:293]: Thank you for the detailed answer on this, that makes a lot of sense.

**Review by adamperlin — CHANGES_REQUESTED** [review]
Just some minor comments

File: cmd/test2json2gha/main.go [hunk 2]
```diff
@@ -145,28 +152,42 @@ func do(in io.Reader, out io.Writer, modName string) (bool, error) {
...
 
-	if te.Action == "fail" {
-		tr.failed = true
+	return failCount > 0, nil
+}
+
+func (c *nopWriteCloser) Close() error { return nil }
+
+func getSummaryFile() io.WriteCloser {
+	v := os.Getenv("GITHUB_STEP_SUMMARY")
```
[the remark this answers is not in the document]
Comment (cpuguy83) [reply cmd/test2json2gha/main.go:178]: Added

File: cmd/test2json2gha/event.go [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+	name    string
+	elapsed float64
+	skipped bool
+}
+
+func (r *TestResult) Close() {
+	r.output.Close()
+}
+
+func handleEvent(te *TestEvent, tr *TestResult) error {
```
[the remark this answers is not in the document]
Comment (cpuguy83) [reply cmd/test2json2gha/event.go]: Changed

**Review by adamperlin — APPROVED** [review]
