### PR TITLE
Fix filepath handling for a few types

### LINKED ISSUE #265: [BUG] Incorrect paths in %files section for a few types
### Expected Behavior

I noticed a few unexpected results in the spec file and rpm after using the latest 0.4.0 tag.

1. If I don't specify a `name` for the artifact config for a binary, I just get the directory in the %files section.
2. The `name` property is ignored for config files and a few other newer types.

EXPECTED:

```
binaries:
    kubernetes/_output/bin/kubelet: {}
```

yields:

```
%files
%{_bindir}/kubelet
```

and:

```
configFiles:
    kubernetes-release/cmd/krel/templates/latest/kubelet/kubelet.env:
      name: kubelet
      subpath: sysconfig
```

yields:

```
%files
%config(noreplace) %{_sysconfdir}/sysconfig/kubelet
```

### Actual Behavior

```
binaries:
    kubernetes/_output/bin/kubelet: {}
```

yields:

```
%files
%{_bindir}
```

While:

```
configFiles:
    kubernetes-release/cmd/krel/templates/latest/kubelet/kubelet.env:
      name: kubelet
      subpath: sysconfig
```

yields:

```
%files
%config(noreplace) %{_sysconfdir}/sysconfig/kubelet.env
```

### Steps To Reproduce

_No response_

### Are you willing to submit PRs to contribute to this bug fix?

- [X] Yes, I am willing to implement it.

### PR DESCRIPTION
**Pull request by jeremyrickard**
**What this PR does / why we need it**:

This PR corrects a few unexpected results when generating a package 

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #265 

**Special notes for your reviewer**:
55ff43e7480aadaafb09a3da77e49c47a97a2fae refactors a bit to create a new function that will use filepath.Base as default and replace it with cfg.Name if provided

507e531af5ff3c547b6c88e7643111cbbb81e634 changes how license and doc files are handled, because currently they need to be at the root of the buildroot unless a subpath was specified

### CODE REVIEW

File: frontend/rpm/template.go [hunk 1]
```diff
@@ -537,3 +519,11 @@ func WriteSpec(spec *dalec.Spec, target string, w io.Writer) error {
 	}
 	return nil
 }
+
+func resolveFileName(path string, cfg dalec.ArtifactConfig) string {
```
Comment (adamperlin) [inline frontend/rpm/template.go:523]: in the systemd PR I actually added a `ResolveName` method to `ArtifactConfig` that does exactly this, maybe you could use that instead?

Comment (jeremyrickard) [reply frontend/rpm/template.go:523]: Thanks for pointing that out!

File: frontend/rpm/template_test.go [hunk 2]
```diff
@@ -209,18 +209,116 @@ func TestTemplateSources(t *testing.T) {
...
-	want := `%postun
+		got := w.PostUn().String()
+		want := `%postun
 %systemd_postun test.service
 `
-	assert.Equal(t, want, got)
+		assert.Equal(t, want, got)
+	})
+
+	t.Run("test doc templaing using artifact config", func(t *testing.T) {
```
Comment (adamperlin) [inline frontend/rpm/template_test.go:229]: nit for these tests: s/templaing/templating

**Comment by cpuguy83** [comment]
Looks good after @adamperlin's comment is fixed.

File: frontend/rpm/template_test.go (hunk 2 above)
Comment (jeremyrickard) [reply frontend/rpm/template_test.go]: doh...sorry!

**Review by cpuguy83 — APPROVED** [review]
