### PR TITLE
Force evaluation before test execution

### LINKED ISSUE #400: Force the state to be evaluated before running package tests
Right now the solved state for packages and containers are not actually evaluated until it hits the test runner, which itself forces evaluation since it needs to inspect some of the real state.
This can make the errors confusing since it looks like a test failed when in reality the build just failed.

Since we are always going to need to evaluate the state to run tests (assuming there are tests), we should just always force the evaluation before passing it off to the test runner.

### PR DESCRIPTION
**Pull request by cpuguy83**
This makes it so error messages from the build are not wrapped in error messages for tests.

Before this change the build is performed lazily until the point when the tests try to interact with the rootfs under test making it appear like a build failure is a test error when in reality we didn't even get to the test.

Closes #400

### CODE REVIEW

File: frontend/azlinux/handle_rpm.go [hunk 1]
```diff
@@ -49,6 +49,10 @@ func handleRPM(w worker) gwclient.BuildFunc {
 				return nil, nil, err
 			}
 
+			if err := ref.Evaluate(ctx); err != nil {
```
Comment (adamperlin) [inline frontend/azlinux/handle_rpm.go:52]: Since `runTests` now constructs the state that installs packages in the target container, this will actually unlazy the package build before the install in the target container, right?

Comment (cpuguy83) [reply frontend/azlinux/handle_rpm.go:52]: Correct.

File: frontend/test_runner.go [hunk 2]
```diff
@@ -41,6 +41,14 @@ func RunTests(ctx context.Context, client gwclient.Client, spec *dalec.Spec, ref
 		return nil
 	}
 
+	if err := ref.Evaluate(ctx); err != nil {
```
Comment (adamperlin) [inline frontend/test_runner.go:44]: Since we're already doing `ref.Evaluate` after we create package build state for `deb`/`rpm`, really the only extra errors this will surface here would be install errors from installing the package in the target container, correct? That should in general be the only extra state that hasn't yet been solved at this point?

Comment (cpuguy83) [reply frontend/test_runner.go:44]: At this point, the package build state is only evaluated on the packaging build targets, not the container targets.
But other than that, yes you are correct.

Comment (adamperlin) [reply frontend/test_runner.go:44]: Ah got it, the build state hasn't yet been evaluated if we've reached this code path from a container target. And in the case of packaging build targets, this `ref.Evaluate` would actually surface errors from installing in the **test** container, not the **target** container since there is no target container in that case. Thanks for clarifying

**Review by adamperlin — APPROVED** [review]
I think this LGTM!
