### PR TITLE
sourcemap.go: don't pass empty output state to SourceMap

### LINKED ISSUE #930: [BUG] g.Cargohome._sourceMap.GetLocation(in) generates invalid LLB input state
### Expected Behavior

Every state generated by Dalec to be serializable to LLB state and OPs.

### Actual Behavior

At the moment calling `ToState()` on a reference generated in test `TestSourceWithCargohome/multi-module` returns an error `invalid nil input definition to definition op`.

I've traced it down to `llb.NewSourceMap(st, sm.filename, sm.language, sm.data)` call in `sourceMap.getLocation()`. Replacing placed state with `nil` actually makes the error go way, so I assume the state is not compatible with filenames we pass or something else is missing.

This seems to me like we generate incorrect LLB state.

### Steps To Reproduce

1. Add the following patch:
```diff
diff --git test/source_test.go test/source_test.go
index fd6732f..eb1dcf3 100644
--- test/source_test.go
+++ test/source_test.go
@@ -760,7 +760,6 @@ index ea874f5..ba38f84 100644
                                stat, err := ref.StatFile(ctx, gwclient.StatRequest{
                                        Path: dep,
                                })
-
                                if err != nil {
                                        t.Fatal(err)
                                }
@@ -1013,12 +1012,17 @@ func TestSourceWithCargohome(t *testing.T) {

                runTest(t, func(ctx context.Context, gwc gwclient.Client) {
                        req := newSolveRequest(withSpec(ctx, t, spec), withBuildContext(ctx, t, contextName, contextSt), withBuildTarget("debug/cargohome"))
+
                        res := solveT(ctx, t, gwc, req)
                        ref, err := res.SingleRef()
                        if err != nil {
                                t.Fatal(err)
                        }

+                       if _, err := ref.ToState(); err != nil {
+                               t.Fatal(err)
+                       }
+
                        // Check that the registry directory exists
                        stat, err := ref.StatFile(ctx, gwclient.StatRequest{
                                Path: "registry/index",
```
2. Run `go test -run SourceWithCargohome/multi-module ./test`

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

### PR DESCRIPTION
**Pull request by invidian**
**What this PR does / why we need it**:
As this generates invalid LLB input.

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:

Closes #930

**Special notes for your reviewer**:

### CODE REVIEW

File: sourcemap.go [hunk 1]
```diff
@@ -48,6 +48,11 @@ func (sm *sourceMap) getLocation(st *llb.State) llb.ConstraintsOpt {
 	if sm == nil {
 		return ConstraintsOptFunc(func(*llb.Constraints) {})
 	}
+
+	if st != nil && st.Output() == nil {
```
Comment (cpuguy83) [inline sourcemap.go:54]: Can you add a comment here?

Comment (invidian) [reply sourcemap.go:54]: Done.
